//REGISTER
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

//Login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";

//Role
export const ROLE_USER = "ROLE_USER";
export const ROLE_USER_ERROR = "ROLE_USER_ERROR";

//CITIES
export const CITIES_LOADING = "CITIES_LOADING";
export const CITIES_SUCCESS = "CITIES_SUCCESS";
export const CITIES_ERROR = "CITIES_ERROR";

//District
export const DISTRICT_LOADING = "DISTRICT_LOADING";
export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_ERROR = "DISTRICT_ERROR";

//Information User is Logined
export const USER_IS_LOGINED_LOADING = "USER_IS_LOGINED_LOADING";
export const USER_IS_LOGINED_SUCCESS = "USER_IS_LOGINED_SUCCESS";
export const USER_IS_LOGINED_ERROR = "USER_IS_LOGINED_ERROR";

//update user
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

//Forgot password
export const FORGOT_PASSWORD_LOADING = "FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

//Change Password
export const CHANGE_PASSWORD_LOADING = "CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

//Vehicle Censorship
export const VEHICLE_CENSORSHIP_LOADING = "VEHICLE_CENSORSHIP_LOADING";
export const VEHICLE_CENSORSHIP_SUCCESS = "VEHICLE_CENSORSHIP_SUCCESS";
export const VEHICLE_CENSORSHIP_ERROR = "VEHICLE_CENSORSHIP_ERROR";

// Create Form Receiver
export const RECEIVER_FORM_CREATE_LOADING = "RECEIVER_FORM_CREATE_LOADING";
export const RECEIVER_FORM_CREATE_SUCCESS = "RECEIVER_FORM_CREATE_SUCCESS";
export const RECEIVER_FORM_CREATE_ERROR = "RECEIVER_FORM_CREATE_ERROR";
export const ESSENTIALS_LOADING = "ESSENTIALS_LOADING";
export const ESSENTIALS_SUCCESS = "ESSENTIALS_SUCCESS";
export const ESSENTIALS_ERROR = "ESSENTIALS_ERROR";

//detail
export const ESSENTIALS_DETAIL_LOADING = "ESSENTIALS_DETAIL_LOADING";
export const ESSENTIALS_DETAIL_SUCCESS = "ESSENTIALS_DETAIL_SUCCESS";
export const ESSENTIALS_DETAIL_ERROR = "ESSENTIALS_DETAIL_ERROR";

// Create Form Sender
export const SENDER_FORM_CREATE_LOADING = "SENDER_FORM_CREATE_LOADING";
export const SENDER_FORM_CREATE_SUCCESS = "SENDER_FORM_CREATE_SUCCESS";
export const SENDER_FORM_CREATE_ERROR = "SENDER_FORM_CREATE_ERROR";

//Status list no complete
export const STATUS_LIST_NO_COMPLETE_LOADING = "STATUS_LIST_NO_COMPLETE_LOADING";
export const STATUS_LIST_NO_COMPLETE_SUCCESS = "STATUS_LIST_NO_COMPLETE_SUCCESS";
export const STATUS_LIST_NO_COMPLETE_ERROR = "STATUS_LIST_NO_COMPLETE_ERROR";

//Sender Status list no complete
export const SENDER_STATUS_LIST_NO_COMPLETE_LOADING = "SENDER_STATUS_LIST_NO_COMPLETE_LOADING";
export const SENDER_STATUS_LIST_NO_COMPLETE_SUCCESS = "SENDER_STATUS_LIST_NO_COMPLETE_SUCCESS";
export const SENDER_STATUS_LIST_NO_COMPLETE_ERROR = "SENDER_STATUS_LIST_NO_COMPLETE_ERROR";

//Receiver Status list no complete
export const RECEIVER_STATUS_LIST_NO_COMPLETE_LOADING = "RECEIVER_STATUS_LIST_NO_COMPLETE_LOADING";
export const RECEIVER_STATUS_LIST_NO_COMPLETE_SUCCESS = "RECEIVER_STATUS_LIST_NO_COMPLETE_SUCCESS";
export const RECEIVER_STATUS_LIST_NO_COMPLETE_ERROR = "RECEIVER_STATUS_LIST_NO_COMPLETE_ERROR";

//Car_trip Status list no complete
export const CAR_TRIP_STATUS_LIST_NO_COMPLETE_LOADING = "CAR_TRIP_STATUS_LIST_NO_COMPLETE_LOADING";
export const CAR_TRIP_STATUS_LIST_NO_COMPLETE_SUCCESS = "CAR_TRIP_STATUS_LIST_NO_COMPLETE_SUCCESS";
export const CAR_TRIP_STATUS_LIST_NO_COMPLETE_ERROR = "CAR_TRIP_STATUS_LIST_NO_COMPLETE_ERROR";

// Status Detail
export const STATUS_DETAIL_LOADING = "STATUS_DETAIL_LOADING";
export const STATUS_DETAIL_SUCCESS = "STATUS_DETAIL_SUCCESS";
export const STATUS_DETAIL_ERROR = "STATUS_DETAIL_ERROR";

// Update status receiver
export const UPDATE_STATUS_RECEIVER_LOADING = "UPDATE_STATUS_RECEIVER_LOADING";
export const UPDATE_STATUS_RECEIVER_SUCCESS = "UPDATE_STATUS_RECEIVER_SUCCESS";
export const UPDATE_STATUS_RECEIVER_ERROR = "UPDATE_STATUS_RECEIVER_ERROR";

// Update status sender
export const UPDATE_STATUS_SENDER_LOADING = "UPDATE_STATUS_SENDER_LOADING";
export const UPDATE_STATUS_SENDER_SUCCESS = "UPDATE_STATUS_SENDER_SUCCESS";
export const UPDATE_STATUS_SENDER_ERROR = "UPDATE_STATUS_SENDER_ERROR";


// Update status cartrip
export const UPDATE_STATUS_CARTRIP_LOADING = "UPDATE_STATUS_CARTRIP_LOADING";
export const UPDATE_STATUS_CARTRIP_SUCCESS = "UPDATE_STATUS_CARTRIP_SUCCESS";
export const UPDATE_STATUS_CARTRIP_ERROR = "UPDATE_STATUS_CARTRIP_ERROR";

// Delete status
export const DELETE_STATUS__LOADING = "DELETE_STATUS__LOADING";
export const DELETE_STATUS__SUCCESS = "DELETE_STATUS__SUCCESS";
export const DELETE_STATUS__ERROR = "DELETE_STATUS__ERROR";

// Create CarTrip form
export const CARTRIP_FORM_CREATE_LOADING = "CARTRIP_FORM_CREATE_LOADING";
export const CARTRIP_FORM_CREATE_SUCCESS = "CARTRIP_FORM_CREATE_SUCCESS";
export const CARTRIP_FORM_CREATE_ERROR = "CARTRIP_FORM_CREATE_ERROR";

// status current
export const STATUS_CURRENT_LOADING = "STATUS_CURRENT_LOADING";
export const STATUS_CURRENT_SUCCESS = "STATUS_CURRENT_SUCCESS";
export const STATUS_CURRENT_ERROR = "STATUS_CURRENT_ERROR";

//Sender Status list when car register no complete 0/2
export const SENDER_STATUS_LIST_CAR_REGIS_0_2_LOADING = "SENDER_STATUS_LIST_CAR_REGIS_0_2_LOADING";
export const SENDER_STATUS_LIST_CAR_REGIS_0_2_SUCCESS = "SENDER_STATUS_LIST_CAR_REGIS_0_2_SUCCESS";
export const SENDER_STATUS_LIST_CAR_REGIS_0_2_ERROR = "SENDER_STATUS_LIST_CAR_REGIS_0_2_ERROR";

//Receiver Status list when car register no complete 0/2
export const RECEIVER_STATUS_LIST_CAR_REGIS_0_2_LOADING = "RECEIVER_STATUS_LIST_CAR_REGIS_0_2_LOADING";
export const RECEIVER_STATUS_LIST_CAR_REGIS_0_2_SUCCESS = "RECEIVER_STATUS_LIST_CAR_REGIS_0_2_SUCCESS";
export const RECEIVER_STATUS_LIST_CAR_REGIS_0_2_ERROR = "RECEIVER_STATUS_LIST_CAR_REGIS_0_2_ERROR";

//get recent status.
export const GET_RECENT_STATUS_SUCCESS = 'GET_RECENT_STATUS_SUCCESS';
export const GET_RECENT_STATUS_ERROR = 'GET_RECENT_STATUS_ERROR';
export const GET_RECENT_STATUS_LOADING = 'GET_RECENT_STATUS_LOADING';

//get status list status.
export const GET_STATUS_LIST_SUCCESS = 'GET_STATUS_LIST_SUCCESS';
export const GET_STATUS_LIST_ERROR = 'GET_STATUS_LIST_ERROR';
export const GET_STATUS_LIST_LOADING = 'GET_STATUS_LIST_LOADING';

//get user no censorship
export const GET_USER_LIST_NO_CENSORSHIP_SUCCESS = 'GET_USER_LIST_NO_CENSORSHIP_SUCCESS';
export const GET_USER_LIST_NO_CENSORSHIP_ERROR = 'GET_USER_LIST_NO_CENSORSHIP_ERROR';
export const GET_USER_LIST_NO_CENSORSHIP_LOADING = 'GET_USER_LIST_NO_CENSORSHIP_LOADING';

export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_ERROR = 'USER_DETAIL_ERROR';
export const USER_DETAIL_LOADING = 'USER_DETAIL_LOADING';

export const GET_ACCOUNT_LIST_SUCCESS = 'GET_ACCOUNT_LIST_SUCCESS';
export const GET_ACCOUNT_LIST_ERROR = 'GET_ACCOUNT_LIST_ERROR';
export const GET_ACCOUNT_LIST_LOADING = 'GET_ACCOUNT_LIST_LOADING';

//Lấy danh sách status theo loại mà có sử dụng bộ lọc
export const GET_STATUS_LIST_BY_TYPE_HAVE_FILTER_SUCCESS = 'GET_STATUS_LIST_BY_TYPE_HAVE_FILTER_SUCCESS';
export const GET_STATUS_LIST_BY_TYPE_HAVE_FILTER_ERROR = 'GET_STATUS_LIST_BY_TYPE_HAVE_FILTER_ERROR';
export const GET_STATUS_LIST_BY_TYPE_HAVE_FILTER_LOADING = 'GET_STATUS_LIST_BY_TYPE_HAVE_FILTER_LOADING';

//lấy tất cả lịch sử của một receiver status bằng receiver_status_id
export const GET_ALL_HISTORY_OF_RECEIVER_STATUS_SUCCESS = 'GET_ALL_HISTORY_OF_RECEIVER_STATUS_SUCCESS';
export const GET_ALL_HISTORY_OF_RECEIVER_STATUS_ERROR = 'GET_ALL_HISTORY_OF_RECEIVER_STATUS_ERROR';
export const GET_ALL_HISTORY_OF_RECEIVER_STATUS_LOADING = 'GET_ALL_HISTORY_OF_RECEIVER_STATUS_LOADING';

//lấy tất cả lịch sử của một sender status bằng sender_status_id
export const GET_ALL_HISTORY_OF_SENDER_STATUS_SUCCESS = 'GET_ALL_HISTORY_OF_SENDER_STATUS_SUCCESS';
export const GET_ALL_HISTORY_OF_SENDER_STATUS_ERROR = 'GET_ALL_HISTORY_OF_SENDER_STATUS_ERROR';
export const GET_ALL_HISTORY_OF_SENDER_STATUS_LOADING = 'GET_ALL_HISTORY_OF_SENDER_STATUS_LOADING';

//laays danh sachs report cos filter
export const GET_REPORT_LIST_HAVE_FILTER_SUCCESS = 'GET_REPORT_LIST_HAVE_FILTER_SUCCESS';
export const GET_REPORT_LIST_HAVE_FILTER_ERROR = 'GET_REPORT_LIST_HAVE_FILTER_ERROR';
export const GET_REPORT_LIST_HAVE_FILTER_LOADING = 'GET_REPORT_LIST_HAVE_FILTER_LOADING';

