
//REGISTER
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

//Login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";


//Role
export const ROLE_USER = "ROLE_USER";
export const ROLE_USER_ERROR = "ROLE_USER_ERROR";

//CITIES
export const CITIES_LOADING = "CITIES_LOADING";
export const CITIES_SUCCESS = "CITIES_SUCCESS";
export const CITIES_ERROR = "CITIES_ERROR";

//CITIES
export const DISTRICT_LOADING = "DISTRICT_LOADING";
export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_ERROR = "DISTRICT_ERROR";

//Information User is Logined
export const USER_IS_LOGINED_LOADING = "USER_IS_LOGINED_LOADING";
export const USER_IS_LOGINED_SUCCESS = "USER_IS_LOGINED_SUCCESS";
export const USER_IS_LOGINED_ERROR = "USER_IS_LOGINED_ERROR";

//update user
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

//Forgot password
export const FORGOT_PASSWORD_LOADING="FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR="FORGOT_PASSWORD_ERROR";

//Change Password
export const CHANGE_PASSWORD_LOADING="CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR="CHANGE_PASSWORD_ERROR";

// Create Form Receiver
export const RECEIVER_FORM_CREATE_SUCCESS = "RECEIVER_FORM_CREATE_SUCCESS";
export const RECEIVER_FORM_CREATE_ERROR = "RECEIVER_FORM_CREATE_ERROR";
export const ESSENTIALS_LOADING = "ESSENTIALS_LOADING";
export const ESSENTIALS_SUCCESS = "ESSENTIALS_SUCCESS";
export const ESSENTIALS_ERROR = "ESSENTIALS_ERROR";

