
//REGISTER
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

//Login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";


//Role
export const ROLE_USER = "ROLE_USER";
export const ROLE_USER_ERROR = "ROLE_USER_ERROR";

//CITIES
export const CITIES_LOADING = "CITIES_LOADING";
export const CITIES_SUCCESS = "CITIES_SUCCESS";
export const CITIES_ERROR = "CITIES_ERROR";

//CITIES
export const DISTRICT_LOADING = "DISTRICT_LOADING";
export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_ERROR = "DISTRICT_ERROR";