
SEDCO_USERNAME="sedcoc1se15@gmail.com";
SEDCO_PASSWORD="SEDCOC1SE@15"

MAILER_HOST="smtp.gmail.com"
MAILER_PORT=587
MAILER_SECURE=false

module.exports ={
    SEDCO_USERNAME,
    SEDCO_PASSWORD,
    MAILER_HOST,
    MAILER_PORT,
    MAILER_SECURE,
}